# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸš€âš¡
  
  
  Thank you and congratsğŸ‰ for opening your very first issue in this project. ğŸ‘£ Profile Extension is a profile ğŸ” search engine for accessing my all social media profile in one tap.ğŸ‘¨â€ğŸ’»ğŸ‘©â€. This chrome extension let's you track your profiles on any account in a single click.
  You may submit a PR if you like, make sure to follow our [Pull Request Template](https://github.com/garimasingh128/profext/blob/master/pull_request_template.md).
  If you want to report a bugğŸ please follow our [Issue Template](https://github.com/garimasingh128/profext/tree/develop/.github/ISSUE_TEMPLATE). Also make sure you include steps to reproduce it and be patient while we get back to you.ğŸ˜„
  
  
  Feel free to join our [Gitter Channel](https://gitter.im/NWoC2020/Profext).ğŸ’– We have an active community overthere.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!ğŸ‘‹ Welcome to the project!ğŸ’–
  
  
  Thank you and congratsğŸ‰ for opening your first pull request.ğŸ‘£ Profile Extension is a profile ğŸ” search engine for accessing my all social media profile in one tap.ğŸ‘¨â€ğŸ’»ğŸ‘©â€. This chrome extension let's you track your profiles on any account in a single click.
  We will get back to you as soon as we can ğŸ˜„.
  
  Feel free to join our [Gitter Channel](https://gitter.im/NWoC2020/Profext).ğŸ’– We have an active community overthere.âœ¨ Hope you have a great time there!ğŸ˜„
  
  
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ All the best for your amazing open source journey ahead .ğŸš€